### ISSUE TITLE
Missing metadata in study file

### ISSUE THREAD

**Issue by sbesson** [IDR/idr0040-aymoz-singlecell#3]
In preparation of the publication of this study, a couple of metadata fields are missing from the study file:

- `Study Type` probably requires to mention `timelapse imaging/microscopy`
- `Study PubMed/PMC` I assume the paper is still in the preprint stage
- `Study License` we definitely have imaging data from the submitted published as CC-BY (https://downloads.openmicroscopy.org/images/Micro-Manager/1.4.16/serge/) this might require some confirmation that they are happy with this licensing
- `Experiment Imaging Method` could probably refer to `FBbi_00000246` as other IDR studies
- `Experiment Assay File` requires to refer to the assays file 

Some processed data files were included in the submission. Given the timelines, this is probably not something we can handle in the upcoming IDR release.

**Comment by dominikl** [comment]
Should be addressed now by 001e06cdb and 043cdd193c on  https://github.com/IDR/idr0040-aymoz-singlecell/pull/2 . For `PubMed/PMC`I just added 'TBC' to be filled in later. Or shall I just leave it empty?

**Comment by sbesson** [comment]
I think we are usually leaving fields empty when unknown - see https://github.com/IDR/idr-metadata/blob/0.4.6/idr0038-held-kidneylightsheet/idr0038-study.txt#L24

**Comment by sbesson** [comment]
Fixed by #2
